"""
Experiment Designer — Create quantum experiments from templates.
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
import os
import time

LAMBDA_PHI = 2.176435e-8
THETA_LOCK = 51.843
PHI_THRESHOLD = 0.7734
CHI_PC = 0.946


@dataclass
class ExperimentTemplate:
    name: str
    description: str
    exp_type: str
    parameters: Dict[str, Any]
    parameter_descriptions: Dict[str, str] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)


class ExperimentDesigner:
    """Designs quantum experiments from templates."""

    TEMPLATES: Dict[str, ExperimentTemplate] = {
        "bell_state": ExperimentTemplate(
            name="Bell State Entanglement",
            description="Prepare Bell pair, measure concurrence and CHSH violation",
            exp_type="bell_state",
            parameters={"qubits": 2, "shots": 8192, "chi_phase": True,
                        "backend": "aer_simulator"},
            tags=["entanglement", "foundational"],
        ),
        "ghz_state": ExperimentTemplate(
            name="GHZ State",
            description="N-qubit GHZ state with parity checks",
            exp_type="ghz_state",
            parameters={"qubits": 5, "shots": 8192, "backend": "aer_simulator"},
            tags=["entanglement", "multipartite"],
        ),
        "theta_sweep": ExperimentTemplate(
            name="Theta Parameter Sweep",
            description="Sweep rotation angle to find optimal theta_lock resonance",
            exp_type="theta_sweep",
            parameters={"qubits": 8, "theta_range": [20, 90], "theta_step": 5.0,
                        "shots": 10000, "backend": "aer_simulator"},
            tags=["sweep", "theta_lock"],
        ),
        "theta_lock": ExperimentTemplate(
            name="Theta Lock Fine Scan",
            description="High-resolution scan around theta_lock = 51.843 degrees",
            exp_type="theta_lock",
            parameters={"qubits": 8, "center": 51.843, "range_deg": 4.0,
                        "step_deg": 0.1, "shots": 20000, "backend": "aer_simulator"},
            tags=["verification", "theta_lock"],
        ),
        "chi_pc_witness": ExperimentTemplate(
            name="Chi-PC Entanglement Witness",
            description="Bell state with chi_PC phase conjugation, measure concurrence",
            exp_type="chi_pc",
            parameters={"chi_factors": [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5],
                        "shots": 10000, "backend": "aer_simulator"},
            tags=["entanglement", "chi_pc"],
        ),
        "lambda_phi_test": ExperimentTemplate(
            name="Lambda-Phi Conservation Test",
            description="Verify Lambda-Phi conservation across circuit transformations",
            exp_type="lambda_phi",
            parameters={"qubits": 4, "shots": 10000, "backend": "aer_simulator",
                        "rotation_angles": [0, 30, 45, 51.843, 60, 90]},
            tags=["conservation", "lambda_phi"],
        ),
        "custom": ExperimentTemplate(
            name="Custom Experiment",
            description="Blank template — design your own quantum experiment",
            exp_type="custom",
            parameters={"qubits": 2, "shots": 1024, "backend": "aer_simulator"},
            tags=["custom"],
        ),
    }

    def list_templates(self) -> List[ExperimentTemplate]:
        return list(self.TEMPLATES.values())

    def get_template(self, name: str) -> Optional[ExperimentTemplate]:
        return self.TEMPLATES.get(name)

    def design(self, template_name: str, output_dir: str,
               overrides: Optional[Dict[str, Any]] = None,
               experiment_name: Optional[str] = None) -> str:
        """Generate an experiment script from a template. Returns script path."""
        template = self.TEMPLATES.get(template_name)
        if not template:
            raise ValueError(f"Unknown template: {template_name}")

        params = {**template.parameters}
        if overrides:
            params.update(overrides)

        exp_name = experiment_name or f"{template_name}_{int(time.time())}"
        filename = f"experiment_{exp_name}.py"
        filepath = os.path.join(output_dir, filename)

        code = self._generate_code(template, params)
        os.makedirs(output_dir, exist_ok=True)
        with open(filepath, "w") as f:
            f.write(code)
        return filepath

    def _generate_code(self, template: ExperimentTemplate, params: Dict) -> str:
        lines = [
            f'"""Experiment: {template.name}',
            f'Description: {template.description}',
            f'Type: {template.exp_type}',
            f'Generated by OSIRIS Lab Designer',
            f'"""',
            "",
            f"# Parameters",
        ]
        for k, v in params.items():
            lines.append(f"{k} = {repr(v)}")
        lines.extend([
            "",
            "if __name__ == '__main__':",
            f"    print('Running {template.name}...')",
            f"    print('Parameters:', {repr(params)})",
        ])
        return "\n".join(lines) + "\n"
